[manager]
show_hidden = true

show_symlink = true

[preview]
image_filter = "catmull-rom"

image_quality = 80

ueberzug_scale = 0.75

[opener]
edit = [
  { run = 'nvim "$@"', block = true },
]

play = [
  { run = 'mpv "$@"', orphan = true, for = "unix"},
]
